#include <curl/curl.h>
#include <stdio.h>
#include <string.h>

#include "auth.h"

#define SPOTIFY_TOKEN_URL "https://accounts.spotify.com/api/token"
#define SPOTIFY_REDIRECT_URI_ENCODED "https%3A%2F%2Flilcrespo.github.io%2Fspotify-auth-qr-callback%2F"

typedef struct MemoryBuffer {
    char *data;
    size_t size;
    size_t capacity;
} MemoryBuffer;

static int HexValue(char c)
{
    if(c >= '0' && c <= '9')
        return c - '0';

    if(c >= 'a' && c <= 'f')
        return c - 'a' + 10;

    if(c >= 'A' && c <= 'F')
        return c - 'A' + 10;

    return -1;
}

static int UrlDecode(const char *in, char *out, size_t outSize)
{
    size_t outLen = 0;

    if(outSize == 0)
        return -1;

    while(*in)
    {
        if(outLen + 1 >= outSize)
            return -2;

        if(*in == '%' && in[1] && in[2])
        {
            int hi = HexValue(in[1]);
            int lo = HexValue(in[2]);

            if(hi >= 0 && lo >= 0)
            {
                out[outLen++] = (char)((hi << 4) | lo);
                in += 3;
                continue;
            }
        }

        if(*in == '+')
            out[outLen++] = ' ';
        else
            out[outLen++] = *in;

        in++;
    }

    out[outLen] = '\0';
    return 0;
}

static int JsonExtractShortKey(const char *input, const char *key, char *out, size_t outSize)
{
    char quotedKey[16];
    const char *p;
    size_t len = 0;

    if(!input || !key || !out || outSize == 0)
        return -1;

    snprintf(quotedKey, sizeof(quotedKey), "\"%s\"", key);
    p = strstr(input, quotedKey);

    if(!p)
        return -2;

    p = strchr(p, ':');

    if(!p)
        return -3;

    p++;

    while(*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n')
        p++;

    if(*p != '"')
        return -4;

    p++;

    while(*p && *p != '"')
    {
        if(*p == '\\')
        {
            p++;

            if(!*p)
                break;
        }

        if(len + 1 >= outSize)
            return -5;

        out[len++] = *p++;
        out[len] = '\0';
    }

    return len > 0 ? 0 : -6;
}

static int ExtractUrlParam(const char *input, const char *param, char *out, size_t outSize)
{
    const char *start;
    char needle[32];
    char encodedValue[2048];
    size_t len = 0;

    if(!input || !param || !out || outSize == 0)
        return -1;

    snprintf(needle, sizeof(needle), "%s=", param);
    start = strstr(input, needle);

    if(start)
        start += strlen(needle);
    else
        return -2;

    while(*start == ' ' || *start == '\t' || *start == '\r' || *start == '\n')
        start++;

    while(start[len] &&
          start[len] != '&' &&
          start[len] != '#' &&
          start[len] != ' ' &&
          start[len] != '\t' &&
          start[len] != '\r' &&
          start[len] != '\n')
    {
        if(len + 1 >= sizeof(encodedValue))
            return -3;

        encodedValue[len] = start[len];
        len++;
    }

    encodedValue[len] = '\0';

    if(len == 0)
        return -4;

    return UrlDecode(encodedValue, out, outSize);
}

static int CopyTrimmedInput(const char *input, char *out, size_t outSize)
{
    size_t len = 0;

    if(!input || !out || outSize == 0)
        return -1;

    while(*input == ' ' || *input == '\t' || *input == '\r' || *input == '\n')
        input++;

    while(input[len] &&
          input[len] != ' ' &&
          input[len] != '\t' &&
          input[len] != '\r' &&
          input[len] != '\n')
    {
        if(len + 1 >= outSize)
            return -2;

        out[len] = input[len];
        len++;
    }

    out[len] = '\0';

    return len > 0 ? 0 : -3;
}

int Auth_ExtractCode(const char *input, char *out, size_t outSize)
{
    int ret;

    ret = JsonExtractShortKey(input, "c", out, outSize);
    if(ret == 0)
        return 0;

    ret = JsonExtractShortKey(input, "code", out, outSize);
    if(ret == 0)
        return 0;

    ret = ExtractUrlParam(input, "code", out, outSize);
    if(ret == 0)
        return 0;

    /* Compact QR payload generated by the callback page: c=...&s=... */
    ret = ExtractUrlParam(input, "c", out, outSize);
    if(ret == 0)
        return 0;

    /*
     * Keep manual fallback for a plain pasted authorization code, but do not
     * treat structured payloads such as v=2&n=... or i=1&c=... as full codes.
     */
    if(strchr(input, '=') || strchr(input, '{') || strstr(input, "://"))
        return -10;

    return CopyTrimmedInput(input, out, outSize);
}

int Auth_ExtractState(const char *input, char *out, size_t outSize)
{
    int ret;

    ret = JsonExtractShortKey(input, "s", out, outSize);
    if(ret == 0)
        return 0;

    ret = JsonExtractShortKey(input, "state", out, outSize);
    if(ret == 0)
        return 0;

    ret = ExtractUrlParam(input, "state", out, outSize);
    if(ret == 0)
        return 0;

    /* Compact QR payload generated by the callback page: c=...&s=... */
    return ExtractUrlParam(input, "s", out, outSize);
}

static size_t Curl_WriteCallback(void *contents, size_t size, size_t nmemb, void *userp)
{
    size_t realSize = size * nmemb;
    MemoryBuffer *mem = (MemoryBuffer *)userp;

    if(mem->size + realSize + 1 > mem->capacity)
        return 0;

    memcpy(mem->data + mem->size, contents, realSize);
    mem->size += realSize;
    mem->data[mem->size] = '\0';

    return realSize;
}

int Auth_ExchangeCode(
    const char *clientId,
    const char *code,
    const char *codeVerifier,
    char *response,
    size_t responseSize,
    long *httpCode
)
{
    CURL *curl;
    CURLcode res;
    struct curl_slist *headers = NULL;

    char *escapedClientId = NULL;
    char *escapedCode = NULL;
    char *escapedVerifier = NULL;

    char postFields[4096];

    MemoryBuffer mem = {
        .data = response,
        .size = 0,
        .capacity = responseSize
    };

    if(!clientId || !code || !codeVerifier || !response || responseSize == 0 || !httpCode)
        return -1;

    response[0] = '\0';
    *httpCode = 0;

    curl = curl_easy_init();

    if(!curl)
        return -2;

    escapedClientId = curl_easy_escape(curl, clientId, 0);
    escapedCode = curl_easy_escape(curl, code, 0);
    escapedVerifier = curl_easy_escape(curl, codeVerifier, 0);

    if(!escapedClientId || !escapedCode || !escapedVerifier)
    {
        if(escapedClientId) curl_free(escapedClientId);
        if(escapedCode) curl_free(escapedCode);
        if(escapedVerifier) curl_free(escapedVerifier);
        curl_easy_cleanup(curl);
        return -3;
    }

    snprintf(
        postFields,
        sizeof(postFields),
        "client_id=%s"
        "&grant_type=authorization_code"
        "&code=%s"
        "&redirect_uri=%s"
        "&code_verifier=%s",
        escapedClientId,
        escapedCode,
        SPOTIFY_REDIRECT_URI_ENCODED,
        escapedVerifier
    );

    headers = curl_slist_append(headers, "Content-Type: application/x-www-form-urlencoded");

    curl_easy_setopt(curl, CURLOPT_URL, SPOTIFY_TOKEN_URL);
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
    curl_easy_setopt(curl, CURLOPT_POSTFIELDS, postFields);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, Curl_WriteCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &mem);
    curl_easy_setopt(curl, CURLOPT_USERAGENT, "SpotifySetup3DS/1.0");

    res = curl_easy_perform(curl);

    curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, httpCode);

    curl_slist_free_all(headers);
    curl_free(escapedClientId);
    curl_free(escapedCode);
    curl_free(escapedVerifier);
    curl_easy_cleanup(curl);

    if(res != CURLE_OK)
        return -4;

    if(*httpCode != 200)
        return -5;

    return 0;
}

int Json_GetString(const char *json, const char *key, char *out, size_t outSize)
{
    const char *p;
    size_t len = 0;

    if(!json || !key || !out || outSize == 0)
        return -1;

    out[0] = '\0';

    p = strstr(json, key);

    if(!p)
        return -2;

    p = strchr(p, ':');

    if(!p)
        return -3;

    p++;

    while(*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n')
        p++;

    if(*p != '"')
        return -4;

    p++;

    while(*p && *p != '"')
    {
        if(*p == '\\')
        {
            p++;

            if(!*p)
                break;
        }

        if(len + 1 >= outSize)
            return -5;

        out[len++] = *p++;
        out[len] = '\0';
    }

    return len > 0 ? 0 : -6;
}